/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ExerciseCreate,
  ExerciseRead,
  ExerciseUpdate,
  HTTPValidationError,
  ListExercisesParams,
  MessageResponse
} from '../model';

import { api } from '../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List Exercises
 */
export type listExercisesResponse200 = {
  data: ExerciseRead[]
  status: 200
}

export type listExercisesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listExercisesResponseSuccess = (listExercisesResponse200) & {
  headers: Headers;
};
export type listExercisesResponseError = (listExercisesResponse422) & {
  headers: Headers;
};

export type listExercisesResponse = (listExercisesResponseSuccess | listExercisesResponseError)

export const getListExercisesUrl = (params?: ListExercisesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/exercises?${stringifiedParams}` : `/api/v1/exercises`
}

export const listExercises = async (params?: ListExercisesParams, options?: RequestInit): Promise<listExercisesResponse> => {
  
  return api<listExercisesResponse>(getListExercisesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getListExercisesQueryKey = (params?: ListExercisesParams,) => {
    return [
    `/api/v1/exercises`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListExercisesQueryOptions = <TData = Awaited<ReturnType<typeof listExercises>>, TError = HTTPValidationError>(params?: ListExercisesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExercises>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListExercisesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listExercises>>> = ({ signal }) => listExercises(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listExercises>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListExercisesQueryResult = NonNullable<Awaited<ReturnType<typeof listExercises>>>
export type ListExercisesQueryError = HTTPValidationError


export function useListExercises<TData = Awaited<ReturnType<typeof listExercises>>, TError = HTTPValidationError>(
 params: undefined |  ListExercisesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExercises>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listExercises>>,
          TError,
          Awaited<ReturnType<typeof listExercises>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListExercises<TData = Awaited<ReturnType<typeof listExercises>>, TError = HTTPValidationError>(
 params?: ListExercisesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExercises>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listExercises>>,
          TError,
          Awaited<ReturnType<typeof listExercises>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListExercises<TData = Awaited<ReturnType<typeof listExercises>>, TError = HTTPValidationError>(
 params?: ListExercisesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExercises>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Exercises
 */

export function useListExercises<TData = Awaited<ReturnType<typeof listExercises>>, TError = HTTPValidationError>(
 params?: ListExercisesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExercises>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListExercisesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Exercise
 */
export type createExerciseResponse201 = {
  data: ExerciseRead
  status: 201
}

export type createExerciseResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createExerciseResponseSuccess = (createExerciseResponse201) & {
  headers: Headers;
};
export type createExerciseResponseError = (createExerciseResponse422) & {
  headers: Headers;
};

export type createExerciseResponse = (createExerciseResponseSuccess | createExerciseResponseError)

export const getCreateExerciseUrl = () => {


  

  return `/api/v1/exercises`
}

export const createExercise = async (exerciseCreate: ExerciseCreate, options?: RequestInit): Promise<createExerciseResponse> => {
  
  return api<createExerciseResponse>(getCreateExerciseUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      exerciseCreate,)
  }
);}
  



export const getCreateExerciseMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createExercise>>, TError,{data: ExerciseCreate}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof createExercise>>, TError,{data: ExerciseCreate}, TContext> => {

const mutationKey = ['createExercise'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createExercise>>, {data: ExerciseCreate}> = (props) => {
          const {data} = props ?? {};

          return  createExercise(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateExerciseMutationResult = NonNullable<Awaited<ReturnType<typeof createExercise>>>
    export type CreateExerciseMutationBody = ExerciseCreate
    export type CreateExerciseMutationError = HTTPValidationError

    /**
 * @summary Create Exercise
 */
export const useCreateExercise = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createExercise>>, TError,{data: ExerciseCreate}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createExercise>>,
        TError,
        {data: ExerciseCreate},
        TContext
      > => {
      return useMutation(getCreateExerciseMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Exercise
 */
export type getExerciseResponse200 = {
  data: ExerciseRead
  status: 200
}

export type getExerciseResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getExerciseResponseSuccess = (getExerciseResponse200) & {
  headers: Headers;
};
export type getExerciseResponseError = (getExerciseResponse422) & {
  headers: Headers;
};

export type getExerciseResponse = (getExerciseResponseSuccess | getExerciseResponseError)

export const getGetExerciseUrl = (exerciseId: number,) => {


  

  return `/api/v1/exercises/${exerciseId}`
}

export const getExercise = async (exerciseId: number, options?: RequestInit): Promise<getExerciseResponse> => {
  
  return api<getExerciseResponse>(getGetExerciseUrl(exerciseId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetExerciseQueryKey = (exerciseId: number,) => {
    return [
    `/api/v1/exercises/${exerciseId}`
    ] as const;
    }

    
export const getGetExerciseQueryOptions = <TData = Awaited<ReturnType<typeof getExercise>>, TError = HTTPValidationError>(exerciseId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExercise>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetExerciseQueryKey(exerciseId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getExercise>>> = ({ signal }) => getExercise(exerciseId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(exerciseId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getExercise>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetExerciseQueryResult = NonNullable<Awaited<ReturnType<typeof getExercise>>>
export type GetExerciseQueryError = HTTPValidationError


export function useGetExercise<TData = Awaited<ReturnType<typeof getExercise>>, TError = HTTPValidationError>(
 exerciseId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExercise>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExercise>>,
          TError,
          Awaited<ReturnType<typeof getExercise>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExercise<TData = Awaited<ReturnType<typeof getExercise>>, TError = HTTPValidationError>(
 exerciseId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExercise>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExercise>>,
          TError,
          Awaited<ReturnType<typeof getExercise>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExercise<TData = Awaited<ReturnType<typeof getExercise>>, TError = HTTPValidationError>(
 exerciseId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExercise>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Exercise
 */

export function useGetExercise<TData = Awaited<ReturnType<typeof getExercise>>, TError = HTTPValidationError>(
 exerciseId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExercise>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetExerciseQueryOptions(exerciseId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update Exercise
 */
export type updateExerciseResponse200 = {
  data: ExerciseRead
  status: 200
}

export type updateExerciseResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateExerciseResponseSuccess = (updateExerciseResponse200) & {
  headers: Headers;
};
export type updateExerciseResponseError = (updateExerciseResponse422) & {
  headers: Headers;
};

export type updateExerciseResponse = (updateExerciseResponseSuccess | updateExerciseResponseError)

export const getUpdateExerciseUrl = (exerciseId: number,) => {


  

  return `/api/v1/exercises/${exerciseId}`
}

export const updateExercise = async (exerciseId: number,
    exerciseUpdate: ExerciseUpdate, options?: RequestInit): Promise<updateExerciseResponse> => {
  
  return api<updateExerciseResponse>(getUpdateExerciseUrl(exerciseId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      exerciseUpdate,)
  }
);}
  



export const getUpdateExerciseMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateExercise>>, TError,{exerciseId: number;data: ExerciseUpdate}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof updateExercise>>, TError,{exerciseId: number;data: ExerciseUpdate}, TContext> => {

const mutationKey = ['updateExercise'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateExercise>>, {exerciseId: number;data: ExerciseUpdate}> = (props) => {
          const {exerciseId,data} = props ?? {};

          return  updateExercise(exerciseId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateExerciseMutationResult = NonNullable<Awaited<ReturnType<typeof updateExercise>>>
    export type UpdateExerciseMutationBody = ExerciseUpdate
    export type UpdateExerciseMutationError = HTTPValidationError

    /**
 * @summary Update Exercise
 */
export const useUpdateExercise = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateExercise>>, TError,{exerciseId: number;data: ExerciseUpdate}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateExercise>>,
        TError,
        {exerciseId: number;data: ExerciseUpdate},
        TContext
      > => {
      return useMutation(getUpdateExerciseMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Exercise
 */
export type deleteExerciseResponse200 = {
  data: MessageResponse
  status: 200
}

export type deleteExerciseResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteExerciseResponseSuccess = (deleteExerciseResponse200) & {
  headers: Headers;
};
export type deleteExerciseResponseError = (deleteExerciseResponse422) & {
  headers: Headers;
};

export type deleteExerciseResponse = (deleteExerciseResponseSuccess | deleteExerciseResponseError)

export const getDeleteExerciseUrl = (exerciseId: number,) => {


  

  return `/api/v1/exercises/${exerciseId}`
}

export const deleteExercise = async (exerciseId: number, options?: RequestInit): Promise<deleteExerciseResponse> => {
  
  return api<deleteExerciseResponse>(getDeleteExerciseUrl(exerciseId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  



export const getDeleteExerciseMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteExercise>>, TError,{exerciseId: number}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteExercise>>, TError,{exerciseId: number}, TContext> => {

const mutationKey = ['deleteExercise'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteExercise>>, {exerciseId: number}> = (props) => {
          const {exerciseId} = props ?? {};

          return  deleteExercise(exerciseId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteExerciseMutationResult = NonNullable<Awaited<ReturnType<typeof deleteExercise>>>
    
    export type DeleteExerciseMutationError = HTTPValidationError

    /**
 * @summary Delete Exercise
 */
export const useDeleteExercise = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteExercise>>, TError,{exerciseId: number}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteExercise>>,
        TError,
        {exerciseId: number},
        TContext
      > => {
      return useMutation(getDeleteExerciseMutationOptions(options), queryClient);
    }
    