/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminListExercisesParams,
  ExerciseCreate,
  ExerciseRead,
  ExerciseUpdate,
  HTTPValidationError,
  MessageResponse
} from '../model';

import { api } from '../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Admin List Exercises
 */
export type adminListExercisesResponse200 = {
  data: ExerciseRead[]
  status: 200
}

export type adminListExercisesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListExercisesResponseSuccess = (adminListExercisesResponse200) & {
  headers: Headers;
};
export type adminListExercisesResponseError = (adminListExercisesResponse422) & {
  headers: Headers;
};

export type adminListExercisesResponse = (adminListExercisesResponseSuccess | adminListExercisesResponseError)

export const getAdminListExercisesUrl = (params?: AdminListExercisesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/exercises?${stringifiedParams}` : `/api/v1/admin/exercises`
}

export const adminListExercises = async (params?: AdminListExercisesParams, options?: RequestInit): Promise<adminListExercisesResponse> => {
  
  return api<adminListExercisesResponse>(getAdminListExercisesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getAdminListExercisesQueryKey = (params?: AdminListExercisesParams,) => {
    return [
    `/api/v1/admin/exercises`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getAdminListExercisesQueryOptions = <TData = Awaited<ReturnType<typeof adminListExercises>>, TError = HTTPValidationError>(params?: AdminListExercisesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListExercises>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListExercisesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListExercises>>> = ({ signal }) => adminListExercises(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListExercises>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListExercisesQueryResult = NonNullable<Awaited<ReturnType<typeof adminListExercises>>>
export type AdminListExercisesQueryError = HTTPValidationError


export function useAdminListExercises<TData = Awaited<ReturnType<typeof adminListExercises>>, TError = HTTPValidationError>(
 params: undefined |  AdminListExercisesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListExercises>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListExercises>>,
          TError,
          Awaited<ReturnType<typeof adminListExercises>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListExercises<TData = Awaited<ReturnType<typeof adminListExercises>>, TError = HTTPValidationError>(
 params?: AdminListExercisesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListExercises>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListExercises>>,
          TError,
          Awaited<ReturnType<typeof adminListExercises>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListExercises<TData = Awaited<ReturnType<typeof adminListExercises>>, TError = HTTPValidationError>(
 params?: AdminListExercisesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListExercises>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Admin List Exercises
 */

export function useAdminListExercises<TData = Awaited<ReturnType<typeof adminListExercises>>, TError = HTTPValidationError>(
 params?: AdminListExercisesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListExercises>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListExercisesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Admin Create Exercise
 */
export type adminCreateExerciseResponse201 = {
  data: ExerciseRead
  status: 201
}

export type adminCreateExerciseResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCreateExerciseResponseSuccess = (adminCreateExerciseResponse201) & {
  headers: Headers;
};
export type adminCreateExerciseResponseError = (adminCreateExerciseResponse422) & {
  headers: Headers;
};

export type adminCreateExerciseResponse = (adminCreateExerciseResponseSuccess | adminCreateExerciseResponseError)

export const getAdminCreateExerciseUrl = () => {


  

  return `/api/v1/admin/exercises`
}

export const adminCreateExercise = async (exerciseCreate: ExerciseCreate, options?: RequestInit): Promise<adminCreateExerciseResponse> => {
  
  return api<adminCreateExerciseResponse>(getAdminCreateExerciseUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      exerciseCreate,)
  }
);}
  



export const getAdminCreateExerciseMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateExercise>>, TError,{data: ExerciseCreate}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof adminCreateExercise>>, TError,{data: ExerciseCreate}, TContext> => {

const mutationKey = ['adminCreateExercise'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateExercise>>, {data: ExerciseCreate}> = (props) => {
          const {data} = props ?? {};

          return  adminCreateExercise(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AdminCreateExerciseMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateExercise>>>
    export type AdminCreateExerciseMutationBody = ExerciseCreate
    export type AdminCreateExerciseMutationError = HTTPValidationError

    /**
 * @summary Admin Create Exercise
 */
export const useAdminCreateExercise = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateExercise>>, TError,{data: ExerciseCreate}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCreateExercise>>,
        TError,
        {data: ExerciseCreate},
        TContext
      > => {
      return useMutation(getAdminCreateExerciseMutationOptions(options), queryClient);
    }
    /**
 * @summary Admin Get Exercise
 */
export type adminGetExerciseResponse200 = {
  data: ExerciseRead
  status: 200
}

export type adminGetExerciseResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminGetExerciseResponseSuccess = (adminGetExerciseResponse200) & {
  headers: Headers;
};
export type adminGetExerciseResponseError = (adminGetExerciseResponse422) & {
  headers: Headers;
};

export type adminGetExerciseResponse = (adminGetExerciseResponseSuccess | adminGetExerciseResponseError)

export const getAdminGetExerciseUrl = (exerciseId: number,) => {


  

  return `/api/v1/admin/exercises/${exerciseId}`
}

export const adminGetExercise = async (exerciseId: number, options?: RequestInit): Promise<adminGetExerciseResponse> => {
  
  return api<adminGetExerciseResponse>(getAdminGetExerciseUrl(exerciseId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getAdminGetExerciseQueryKey = (exerciseId: number,) => {
    return [
    `/api/v1/admin/exercises/${exerciseId}`
    ] as const;
    }

    
export const getAdminGetExerciseQueryOptions = <TData = Awaited<ReturnType<typeof adminGetExercise>>, TError = HTTPValidationError>(exerciseId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetExercise>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminGetExerciseQueryKey(exerciseId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetExercise>>> = ({ signal }) => adminGetExercise(exerciseId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(exerciseId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminGetExercise>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminGetExerciseQueryResult = NonNullable<Awaited<ReturnType<typeof adminGetExercise>>>
export type AdminGetExerciseQueryError = HTTPValidationError


export function useAdminGetExercise<TData = Awaited<ReturnType<typeof adminGetExercise>>, TError = HTTPValidationError>(
 exerciseId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetExercise>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetExercise>>,
          TError,
          Awaited<ReturnType<typeof adminGetExercise>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetExercise<TData = Awaited<ReturnType<typeof adminGetExercise>>, TError = HTTPValidationError>(
 exerciseId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetExercise>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetExercise>>,
          TError,
          Awaited<ReturnType<typeof adminGetExercise>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetExercise<TData = Awaited<ReturnType<typeof adminGetExercise>>, TError = HTTPValidationError>(
 exerciseId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetExercise>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Admin Get Exercise
 */

export function useAdminGetExercise<TData = Awaited<ReturnType<typeof adminGetExercise>>, TError = HTTPValidationError>(
 exerciseId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetExercise>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminGetExerciseQueryOptions(exerciseId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Admin Update Exercise
 */
export type adminUpdateExerciseResponse200 = {
  data: ExerciseRead
  status: 200
}

export type adminUpdateExerciseResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminUpdateExerciseResponseSuccess = (adminUpdateExerciseResponse200) & {
  headers: Headers;
};
export type adminUpdateExerciseResponseError = (adminUpdateExerciseResponse422) & {
  headers: Headers;
};

export type adminUpdateExerciseResponse = (adminUpdateExerciseResponseSuccess | adminUpdateExerciseResponseError)

export const getAdminUpdateExerciseUrl = (exerciseId: number,) => {


  

  return `/api/v1/admin/exercises/${exerciseId}`
}

export const adminUpdateExercise = async (exerciseId: number,
    exerciseUpdate: ExerciseUpdate, options?: RequestInit): Promise<adminUpdateExerciseResponse> => {
  
  return api<adminUpdateExerciseResponse>(getAdminUpdateExerciseUrl(exerciseId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      exerciseUpdate,)
  }
);}
  



export const getAdminUpdateExerciseMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateExercise>>, TError,{exerciseId: number;data: ExerciseUpdate}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateExercise>>, TError,{exerciseId: number;data: ExerciseUpdate}, TContext> => {

const mutationKey = ['adminUpdateExercise'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateExercise>>, {exerciseId: number;data: ExerciseUpdate}> = (props) => {
          const {exerciseId,data} = props ?? {};

          return  adminUpdateExercise(exerciseId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdateExerciseMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateExercise>>>
    export type AdminUpdateExerciseMutationBody = ExerciseUpdate
    export type AdminUpdateExerciseMutationError = HTTPValidationError

    /**
 * @summary Admin Update Exercise
 */
export const useAdminUpdateExercise = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateExercise>>, TError,{exerciseId: number;data: ExerciseUpdate}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdateExercise>>,
        TError,
        {exerciseId: number;data: ExerciseUpdate},
        TContext
      > => {
      return useMutation(getAdminUpdateExerciseMutationOptions(options), queryClient);
    }
    /**
 * @summary Admin Delete Exercise
 */
export type adminDeleteExerciseResponse200 = {
  data: MessageResponse
  status: 200
}

export type adminDeleteExerciseResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminDeleteExerciseResponseSuccess = (adminDeleteExerciseResponse200) & {
  headers: Headers;
};
export type adminDeleteExerciseResponseError = (adminDeleteExerciseResponse422) & {
  headers: Headers;
};

export type adminDeleteExerciseResponse = (adminDeleteExerciseResponseSuccess | adminDeleteExerciseResponseError)

export const getAdminDeleteExerciseUrl = (exerciseId: number,) => {


  

  return `/api/v1/admin/exercises/${exerciseId}`
}

export const adminDeleteExercise = async (exerciseId: number, options?: RequestInit): Promise<adminDeleteExerciseResponse> => {
  
  return api<adminDeleteExerciseResponse>(getAdminDeleteExerciseUrl(exerciseId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  



export const getAdminDeleteExerciseMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDeleteExercise>>, TError,{exerciseId: number}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof adminDeleteExercise>>, TError,{exerciseId: number}, TContext> => {

const mutationKey = ['adminDeleteExercise'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminDeleteExercise>>, {exerciseId: number}> = (props) => {
          const {exerciseId} = props ?? {};

          return  adminDeleteExercise(exerciseId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AdminDeleteExerciseMutationResult = NonNullable<Awaited<ReturnType<typeof adminDeleteExercise>>>
    
    export type AdminDeleteExerciseMutationError = HTTPValidationError

    /**
 * @summary Admin Delete Exercise
 */
export const useAdminDeleteExercise = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDeleteExercise>>, TError,{exerciseId: number}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminDeleteExercise>>,
        TError,
        {exerciseId: number},
        TContext
      > => {
      return useMutation(getAdminDeleteExerciseMutationOptions(options), queryClient);
    }
    