/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  MessageResponse,
  PlanExerciseCreate,
  PlanExerciseRead,
  PlanExerciseReorder,
  WorkoutPlanCreate,
  WorkoutPlanRead,
  WorkoutPlanUpdate
} from '../model';

import { api } from '../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List Workout Plans
 */
export type listWorkoutPlansResponse200 = {
  data: WorkoutPlanRead[]
  status: 200
}

export type listWorkoutPlansResponseSuccess = (listWorkoutPlansResponse200) & {
  headers: Headers;
};
;

export type listWorkoutPlansResponse = (listWorkoutPlansResponseSuccess)

export const getListWorkoutPlansUrl = () => {


  

  return `/api/v1/workout-plans`
}

export const listWorkoutPlans = async ( options?: RequestInit): Promise<listWorkoutPlansResponse> => {
  
  return api<listWorkoutPlansResponse>(getListWorkoutPlansUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getListWorkoutPlansQueryKey = () => {
    return [
    `/api/v1/workout-plans`
    ] as const;
    }

    
export const getListWorkoutPlansQueryOptions = <TData = Awaited<ReturnType<typeof listWorkoutPlans>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkoutPlans>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListWorkoutPlansQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listWorkoutPlans>>> = ({ signal }) => listWorkoutPlans({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listWorkoutPlans>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListWorkoutPlansQueryResult = NonNullable<Awaited<ReturnType<typeof listWorkoutPlans>>>
export type ListWorkoutPlansQueryError = unknown


export function useListWorkoutPlans<TData = Awaited<ReturnType<typeof listWorkoutPlans>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkoutPlans>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listWorkoutPlans>>,
          TError,
          Awaited<ReturnType<typeof listWorkoutPlans>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListWorkoutPlans<TData = Awaited<ReturnType<typeof listWorkoutPlans>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkoutPlans>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listWorkoutPlans>>,
          TError,
          Awaited<ReturnType<typeof listWorkoutPlans>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListWorkoutPlans<TData = Awaited<ReturnType<typeof listWorkoutPlans>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkoutPlans>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Workout Plans
 */

export function useListWorkoutPlans<TData = Awaited<ReturnType<typeof listWorkoutPlans>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkoutPlans>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListWorkoutPlansQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Workout Plan
 */
export type createWorkoutPlanResponse201 = {
  data: WorkoutPlanRead
  status: 201
}

export type createWorkoutPlanResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createWorkoutPlanResponseSuccess = (createWorkoutPlanResponse201) & {
  headers: Headers;
};
export type createWorkoutPlanResponseError = (createWorkoutPlanResponse422) & {
  headers: Headers;
};

export type createWorkoutPlanResponse = (createWorkoutPlanResponseSuccess | createWorkoutPlanResponseError)

export const getCreateWorkoutPlanUrl = () => {


  

  return `/api/v1/workout-plans`
}

export const createWorkoutPlan = async (workoutPlanCreate: WorkoutPlanCreate, options?: RequestInit): Promise<createWorkoutPlanResponse> => {
  
  return api<createWorkoutPlanResponse>(getCreateWorkoutPlanUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      workoutPlanCreate,)
  }
);}
  



export const getCreateWorkoutPlanMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWorkoutPlan>>, TError,{data: WorkoutPlanCreate}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof createWorkoutPlan>>, TError,{data: WorkoutPlanCreate}, TContext> => {

const mutationKey = ['createWorkoutPlan'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createWorkoutPlan>>, {data: WorkoutPlanCreate}> = (props) => {
          const {data} = props ?? {};

          return  createWorkoutPlan(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateWorkoutPlanMutationResult = NonNullable<Awaited<ReturnType<typeof createWorkoutPlan>>>
    export type CreateWorkoutPlanMutationBody = WorkoutPlanCreate
    export type CreateWorkoutPlanMutationError = HTTPValidationError

    /**
 * @summary Create Workout Plan
 */
export const useCreateWorkoutPlan = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWorkoutPlan>>, TError,{data: WorkoutPlanCreate}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createWorkoutPlan>>,
        TError,
        {data: WorkoutPlanCreate},
        TContext
      > => {
      return useMutation(getCreateWorkoutPlanMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Workout Plan
 */
export type getWorkoutPlanResponse200 = {
  data: WorkoutPlanRead
  status: 200
}

export type getWorkoutPlanResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getWorkoutPlanResponseSuccess = (getWorkoutPlanResponse200) & {
  headers: Headers;
};
export type getWorkoutPlanResponseError = (getWorkoutPlanResponse422) & {
  headers: Headers;
};

export type getWorkoutPlanResponse = (getWorkoutPlanResponseSuccess | getWorkoutPlanResponseError)

export const getGetWorkoutPlanUrl = (planId: number,) => {


  

  return `/api/v1/workout-plans/${planId}`
}

export const getWorkoutPlan = async (planId: number, options?: RequestInit): Promise<getWorkoutPlanResponse> => {
  
  return api<getWorkoutPlanResponse>(getGetWorkoutPlanUrl(planId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetWorkoutPlanQueryKey = (planId: number,) => {
    return [
    `/api/v1/workout-plans/${planId}`
    ] as const;
    }

    
export const getGetWorkoutPlanQueryOptions = <TData = Awaited<ReturnType<typeof getWorkoutPlan>>, TError = HTTPValidationError>(planId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkoutPlan>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkoutPlanQueryKey(planId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkoutPlan>>> = ({ signal }) => getWorkoutPlan(planId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(planId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkoutPlan>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWorkoutPlanQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkoutPlan>>>
export type GetWorkoutPlanQueryError = HTTPValidationError


export function useGetWorkoutPlan<TData = Awaited<ReturnType<typeof getWorkoutPlan>>, TError = HTTPValidationError>(
 planId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkoutPlan>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkoutPlan>>,
          TError,
          Awaited<ReturnType<typeof getWorkoutPlan>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkoutPlan<TData = Awaited<ReturnType<typeof getWorkoutPlan>>, TError = HTTPValidationError>(
 planId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkoutPlan>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkoutPlan>>,
          TError,
          Awaited<ReturnType<typeof getWorkoutPlan>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkoutPlan<TData = Awaited<ReturnType<typeof getWorkoutPlan>>, TError = HTTPValidationError>(
 planId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkoutPlan>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Workout Plan
 */

export function useGetWorkoutPlan<TData = Awaited<ReturnType<typeof getWorkoutPlan>>, TError = HTTPValidationError>(
 planId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkoutPlan>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWorkoutPlanQueryOptions(planId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update Workout Plan
 */
export type updateWorkoutPlanResponse200 = {
  data: WorkoutPlanRead
  status: 200
}

export type updateWorkoutPlanResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateWorkoutPlanResponseSuccess = (updateWorkoutPlanResponse200) & {
  headers: Headers;
};
export type updateWorkoutPlanResponseError = (updateWorkoutPlanResponse422) & {
  headers: Headers;
};

export type updateWorkoutPlanResponse = (updateWorkoutPlanResponseSuccess | updateWorkoutPlanResponseError)

export const getUpdateWorkoutPlanUrl = (planId: number,) => {


  

  return `/api/v1/workout-plans/${planId}`
}

export const updateWorkoutPlan = async (planId: number,
    workoutPlanUpdate: WorkoutPlanUpdate, options?: RequestInit): Promise<updateWorkoutPlanResponse> => {
  
  return api<updateWorkoutPlanResponse>(getUpdateWorkoutPlanUrl(planId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      workoutPlanUpdate,)
  }
);}
  



export const getUpdateWorkoutPlanMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWorkoutPlan>>, TError,{planId: number;data: WorkoutPlanUpdate}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof updateWorkoutPlan>>, TError,{planId: number;data: WorkoutPlanUpdate}, TContext> => {

const mutationKey = ['updateWorkoutPlan'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateWorkoutPlan>>, {planId: number;data: WorkoutPlanUpdate}> = (props) => {
          const {planId,data} = props ?? {};

          return  updateWorkoutPlan(planId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateWorkoutPlanMutationResult = NonNullable<Awaited<ReturnType<typeof updateWorkoutPlan>>>
    export type UpdateWorkoutPlanMutationBody = WorkoutPlanUpdate
    export type UpdateWorkoutPlanMutationError = HTTPValidationError

    /**
 * @summary Update Workout Plan
 */
export const useUpdateWorkoutPlan = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWorkoutPlan>>, TError,{planId: number;data: WorkoutPlanUpdate}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateWorkoutPlan>>,
        TError,
        {planId: number;data: WorkoutPlanUpdate},
        TContext
      > => {
      return useMutation(getUpdateWorkoutPlanMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Workout Plan
 */
export type deleteWorkoutPlanResponse200 = {
  data: MessageResponse
  status: 200
}

export type deleteWorkoutPlanResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteWorkoutPlanResponseSuccess = (deleteWorkoutPlanResponse200) & {
  headers: Headers;
};
export type deleteWorkoutPlanResponseError = (deleteWorkoutPlanResponse422) & {
  headers: Headers;
};

export type deleteWorkoutPlanResponse = (deleteWorkoutPlanResponseSuccess | deleteWorkoutPlanResponseError)

export const getDeleteWorkoutPlanUrl = (planId: number,) => {


  

  return `/api/v1/workout-plans/${planId}`
}

export const deleteWorkoutPlan = async (planId: number, options?: RequestInit): Promise<deleteWorkoutPlanResponse> => {
  
  return api<deleteWorkoutPlanResponse>(getDeleteWorkoutPlanUrl(planId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  



export const getDeleteWorkoutPlanMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkoutPlan>>, TError,{planId: number}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteWorkoutPlan>>, TError,{planId: number}, TContext> => {

const mutationKey = ['deleteWorkoutPlan'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteWorkoutPlan>>, {planId: number}> = (props) => {
          const {planId} = props ?? {};

          return  deleteWorkoutPlan(planId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteWorkoutPlanMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWorkoutPlan>>>
    
    export type DeleteWorkoutPlanMutationError = HTTPValidationError

    /**
 * @summary Delete Workout Plan
 */
export const useDeleteWorkoutPlan = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkoutPlan>>, TError,{planId: number}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteWorkoutPlan>>,
        TError,
        {planId: number},
        TContext
      > => {
      return useMutation(getDeleteWorkoutPlanMutationOptions(options), queryClient);
    }
    /**
 * @summary Add Plan Exercise
 */
export type addPlanExerciseResponse201 = {
  data: PlanExerciseRead
  status: 201
}

export type addPlanExerciseResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type addPlanExerciseResponseSuccess = (addPlanExerciseResponse201) & {
  headers: Headers;
};
export type addPlanExerciseResponseError = (addPlanExerciseResponse422) & {
  headers: Headers;
};

export type addPlanExerciseResponse = (addPlanExerciseResponseSuccess | addPlanExerciseResponseError)

export const getAddPlanExerciseUrl = (planId: number,) => {


  

  return `/api/v1/workout-plans/${planId}/exercises`
}

export const addPlanExercise = async (planId: number,
    planExerciseCreate: PlanExerciseCreate, options?: RequestInit): Promise<addPlanExerciseResponse> => {
  
  return api<addPlanExerciseResponse>(getAddPlanExerciseUrl(planId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      planExerciseCreate,)
  }
);}
  



export const getAddPlanExerciseMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addPlanExercise>>, TError,{planId: number;data: PlanExerciseCreate}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof addPlanExercise>>, TError,{planId: number;data: PlanExerciseCreate}, TContext> => {

const mutationKey = ['addPlanExercise'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addPlanExercise>>, {planId: number;data: PlanExerciseCreate}> = (props) => {
          const {planId,data} = props ?? {};

          return  addPlanExercise(planId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AddPlanExerciseMutationResult = NonNullable<Awaited<ReturnType<typeof addPlanExercise>>>
    export type AddPlanExerciseMutationBody = PlanExerciseCreate
    export type AddPlanExerciseMutationError = HTTPValidationError

    /**
 * @summary Add Plan Exercise
 */
export const useAddPlanExercise = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addPlanExercise>>, TError,{planId: number;data: PlanExerciseCreate}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addPlanExercise>>,
        TError,
        {planId: number;data: PlanExerciseCreate},
        TContext
      > => {
      return useMutation(getAddPlanExerciseMutationOptions(options), queryClient);
    }
    /**
 * @summary Reorder Plan Exercises
 */
export type reorderPlanExercisesResponse200 = {
  data: MessageResponse
  status: 200
}

export type reorderPlanExercisesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type reorderPlanExercisesResponseSuccess = (reorderPlanExercisesResponse200) & {
  headers: Headers;
};
export type reorderPlanExercisesResponseError = (reorderPlanExercisesResponse422) & {
  headers: Headers;
};

export type reorderPlanExercisesResponse = (reorderPlanExercisesResponseSuccess | reorderPlanExercisesResponseError)

export const getReorderPlanExercisesUrl = (planId: number,) => {


  

  return `/api/v1/workout-plans/${planId}/exercises/reorder`
}

export const reorderPlanExercises = async (planId: number,
    planExerciseReorder: PlanExerciseReorder, options?: RequestInit): Promise<reorderPlanExercisesResponse> => {
  
  return api<reorderPlanExercisesResponse>(getReorderPlanExercisesUrl(planId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      planExerciseReorder,)
  }
);}
  



export const getReorderPlanExercisesMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reorderPlanExercises>>, TError,{planId: number;data: PlanExerciseReorder}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof reorderPlanExercises>>, TError,{planId: number;data: PlanExerciseReorder}, TContext> => {

const mutationKey = ['reorderPlanExercises'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reorderPlanExercises>>, {planId: number;data: PlanExerciseReorder}> = (props) => {
          const {planId,data} = props ?? {};

          return  reorderPlanExercises(planId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ReorderPlanExercisesMutationResult = NonNullable<Awaited<ReturnType<typeof reorderPlanExercises>>>
    export type ReorderPlanExercisesMutationBody = PlanExerciseReorder
    export type ReorderPlanExercisesMutationError = HTTPValidationError

    /**
 * @summary Reorder Plan Exercises
 */
export const useReorderPlanExercises = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reorderPlanExercises>>, TError,{planId: number;data: PlanExerciseReorder}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reorderPlanExercises>>,
        TError,
        {planId: number;data: PlanExerciseReorder},
        TContext
      > => {
      return useMutation(getReorderPlanExercisesMutationOptions(options), queryClient);
    }
    /**
 * @summary Remove Plan Exercise
 */
export type removePlanExerciseResponse200 = {
  data: MessageResponse
  status: 200
}

export type removePlanExerciseResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type removePlanExerciseResponseSuccess = (removePlanExerciseResponse200) & {
  headers: Headers;
};
export type removePlanExerciseResponseError = (removePlanExerciseResponse422) & {
  headers: Headers;
};

export type removePlanExerciseResponse = (removePlanExerciseResponseSuccess | removePlanExerciseResponseError)

export const getRemovePlanExerciseUrl = (planId: number,
    planExerciseId: number,) => {


  

  return `/api/v1/workout-plans/${planId}/exercises/${planExerciseId}`
}

export const removePlanExercise = async (planId: number,
    planExerciseId: number, options?: RequestInit): Promise<removePlanExerciseResponse> => {
  
  return api<removePlanExerciseResponse>(getRemovePlanExerciseUrl(planId,planExerciseId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  



export const getRemovePlanExerciseMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removePlanExercise>>, TError,{planId: number;planExerciseId: number}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof removePlanExercise>>, TError,{planId: number;planExerciseId: number}, TContext> => {

const mutationKey = ['removePlanExercise'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removePlanExercise>>, {planId: number;planExerciseId: number}> = (props) => {
          const {planId,planExerciseId} = props ?? {};

          return  removePlanExercise(planId,planExerciseId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RemovePlanExerciseMutationResult = NonNullable<Awaited<ReturnType<typeof removePlanExercise>>>
    
    export type RemovePlanExerciseMutationError = HTTPValidationError

    /**
 * @summary Remove Plan Exercise
 */
export const useRemovePlanExercise = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removePlanExercise>>, TError,{planId: number;planExerciseId: number}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removePlanExercise>>,
        TError,
        {planId: number;planExerciseId: number},
        TContext
      > => {
      return useMutation(getRemovePlanExerciseMutationOptions(options), queryClient);
    }
    