/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  MessageResponse,
  MuscleGroupCreate,
  MuscleGroupRead,
  MuscleGroupUpdate
} from '../model';

import { api } from '../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List Muscle Groups
 */
export type listMuscleGroupsResponse200 = {
  data: MuscleGroupRead[]
  status: 200
}

export type listMuscleGroupsResponseSuccess = (listMuscleGroupsResponse200) & {
  headers: Headers;
};
;

export type listMuscleGroupsResponse = (listMuscleGroupsResponseSuccess)

export const getListMuscleGroupsUrl = () => {


  

  return `/api/v1/muscle-groups`
}

export const listMuscleGroups = async ( options?: RequestInit): Promise<listMuscleGroupsResponse> => {
  
  return api<listMuscleGroupsResponse>(getListMuscleGroupsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getListMuscleGroupsQueryKey = () => {
    return [
    `/api/v1/muscle-groups`
    ] as const;
    }

    
export const getListMuscleGroupsQueryOptions = <TData = Awaited<ReturnType<typeof listMuscleGroups>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMuscleGroups>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMuscleGroupsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMuscleGroups>>> = ({ signal }) => listMuscleGroups({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMuscleGroups>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMuscleGroupsQueryResult = NonNullable<Awaited<ReturnType<typeof listMuscleGroups>>>
export type ListMuscleGroupsQueryError = unknown


export function useListMuscleGroups<TData = Awaited<ReturnType<typeof listMuscleGroups>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMuscleGroups>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMuscleGroups>>,
          TError,
          Awaited<ReturnType<typeof listMuscleGroups>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMuscleGroups<TData = Awaited<ReturnType<typeof listMuscleGroups>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMuscleGroups>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMuscleGroups>>,
          TError,
          Awaited<ReturnType<typeof listMuscleGroups>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMuscleGroups<TData = Awaited<ReturnType<typeof listMuscleGroups>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMuscleGroups>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Muscle Groups
 */

export function useListMuscleGroups<TData = Awaited<ReturnType<typeof listMuscleGroups>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMuscleGroups>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMuscleGroupsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Muscle Group
 */
export type createMuscleGroupResponse201 = {
  data: MuscleGroupRead
  status: 201
}

export type createMuscleGroupResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createMuscleGroupResponseSuccess = (createMuscleGroupResponse201) & {
  headers: Headers;
};
export type createMuscleGroupResponseError = (createMuscleGroupResponse422) & {
  headers: Headers;
};

export type createMuscleGroupResponse = (createMuscleGroupResponseSuccess | createMuscleGroupResponseError)

export const getCreateMuscleGroupUrl = () => {


  

  return `/api/v1/muscle-groups`
}

export const createMuscleGroup = async (muscleGroupCreate: MuscleGroupCreate, options?: RequestInit): Promise<createMuscleGroupResponse> => {
  
  return api<createMuscleGroupResponse>(getCreateMuscleGroupUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      muscleGroupCreate,)
  }
);}
  



export const getCreateMuscleGroupMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMuscleGroup>>, TError,{data: MuscleGroupCreate}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof createMuscleGroup>>, TError,{data: MuscleGroupCreate}, TContext> => {

const mutationKey = ['createMuscleGroup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMuscleGroup>>, {data: MuscleGroupCreate}> = (props) => {
          const {data} = props ?? {};

          return  createMuscleGroup(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateMuscleGroupMutationResult = NonNullable<Awaited<ReturnType<typeof createMuscleGroup>>>
    export type CreateMuscleGroupMutationBody = MuscleGroupCreate
    export type CreateMuscleGroupMutationError = HTTPValidationError

    /**
 * @summary Create Muscle Group
 */
export const useCreateMuscleGroup = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMuscleGroup>>, TError,{data: MuscleGroupCreate}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createMuscleGroup>>,
        TError,
        {data: MuscleGroupCreate},
        TContext
      > => {
      return useMutation(getCreateMuscleGroupMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Muscle Group
 */
export type getMuscleGroupResponse200 = {
  data: MuscleGroupRead
  status: 200
}

export type getMuscleGroupResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getMuscleGroupResponseSuccess = (getMuscleGroupResponse200) & {
  headers: Headers;
};
export type getMuscleGroupResponseError = (getMuscleGroupResponse422) & {
  headers: Headers;
};

export type getMuscleGroupResponse = (getMuscleGroupResponseSuccess | getMuscleGroupResponseError)

export const getGetMuscleGroupUrl = (muscleGroupId: number,) => {


  

  return `/api/v1/muscle-groups/${muscleGroupId}`
}

export const getMuscleGroup = async (muscleGroupId: number, options?: RequestInit): Promise<getMuscleGroupResponse> => {
  
  return api<getMuscleGroupResponse>(getGetMuscleGroupUrl(muscleGroupId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetMuscleGroupQueryKey = (muscleGroupId: number,) => {
    return [
    `/api/v1/muscle-groups/${muscleGroupId}`
    ] as const;
    }

    
export const getGetMuscleGroupQueryOptions = <TData = Awaited<ReturnType<typeof getMuscleGroup>>, TError = HTTPValidationError>(muscleGroupId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMuscleGroup>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMuscleGroupQueryKey(muscleGroupId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMuscleGroup>>> = ({ signal }) => getMuscleGroup(muscleGroupId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(muscleGroupId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMuscleGroup>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMuscleGroupQueryResult = NonNullable<Awaited<ReturnType<typeof getMuscleGroup>>>
export type GetMuscleGroupQueryError = HTTPValidationError


export function useGetMuscleGroup<TData = Awaited<ReturnType<typeof getMuscleGroup>>, TError = HTTPValidationError>(
 muscleGroupId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMuscleGroup>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMuscleGroup>>,
          TError,
          Awaited<ReturnType<typeof getMuscleGroup>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMuscleGroup<TData = Awaited<ReturnType<typeof getMuscleGroup>>, TError = HTTPValidationError>(
 muscleGroupId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMuscleGroup>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMuscleGroup>>,
          TError,
          Awaited<ReturnType<typeof getMuscleGroup>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMuscleGroup<TData = Awaited<ReturnType<typeof getMuscleGroup>>, TError = HTTPValidationError>(
 muscleGroupId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMuscleGroup>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Muscle Group
 */

export function useGetMuscleGroup<TData = Awaited<ReturnType<typeof getMuscleGroup>>, TError = HTTPValidationError>(
 muscleGroupId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMuscleGroup>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMuscleGroupQueryOptions(muscleGroupId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update Muscle Group
 */
export type updateMuscleGroupResponse200 = {
  data: MuscleGroupRead
  status: 200
}

export type updateMuscleGroupResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateMuscleGroupResponseSuccess = (updateMuscleGroupResponse200) & {
  headers: Headers;
};
export type updateMuscleGroupResponseError = (updateMuscleGroupResponse422) & {
  headers: Headers;
};

export type updateMuscleGroupResponse = (updateMuscleGroupResponseSuccess | updateMuscleGroupResponseError)

export const getUpdateMuscleGroupUrl = (muscleGroupId: number,) => {


  

  return `/api/v1/muscle-groups/${muscleGroupId}`
}

export const updateMuscleGroup = async (muscleGroupId: number,
    muscleGroupUpdate: MuscleGroupUpdate, options?: RequestInit): Promise<updateMuscleGroupResponse> => {
  
  return api<updateMuscleGroupResponse>(getUpdateMuscleGroupUrl(muscleGroupId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      muscleGroupUpdate,)
  }
);}
  



export const getUpdateMuscleGroupMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMuscleGroup>>, TError,{muscleGroupId: number;data: MuscleGroupUpdate}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof updateMuscleGroup>>, TError,{muscleGroupId: number;data: MuscleGroupUpdate}, TContext> => {

const mutationKey = ['updateMuscleGroup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMuscleGroup>>, {muscleGroupId: number;data: MuscleGroupUpdate}> = (props) => {
          const {muscleGroupId,data} = props ?? {};

          return  updateMuscleGroup(muscleGroupId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMuscleGroupMutationResult = NonNullable<Awaited<ReturnType<typeof updateMuscleGroup>>>
    export type UpdateMuscleGroupMutationBody = MuscleGroupUpdate
    export type UpdateMuscleGroupMutationError = HTTPValidationError

    /**
 * @summary Update Muscle Group
 */
export const useUpdateMuscleGroup = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMuscleGroup>>, TError,{muscleGroupId: number;data: MuscleGroupUpdate}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMuscleGroup>>,
        TError,
        {muscleGroupId: number;data: MuscleGroupUpdate},
        TContext
      > => {
      return useMutation(getUpdateMuscleGroupMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Muscle Group
 */
export type deleteMuscleGroupResponse200 = {
  data: MessageResponse
  status: 200
}

export type deleteMuscleGroupResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteMuscleGroupResponseSuccess = (deleteMuscleGroupResponse200) & {
  headers: Headers;
};
export type deleteMuscleGroupResponseError = (deleteMuscleGroupResponse422) & {
  headers: Headers;
};

export type deleteMuscleGroupResponse = (deleteMuscleGroupResponseSuccess | deleteMuscleGroupResponseError)

export const getDeleteMuscleGroupUrl = (muscleGroupId: number,) => {


  

  return `/api/v1/muscle-groups/${muscleGroupId}`
}

export const deleteMuscleGroup = async (muscleGroupId: number, options?: RequestInit): Promise<deleteMuscleGroupResponse> => {
  
  return api<deleteMuscleGroupResponse>(getDeleteMuscleGroupUrl(muscleGroupId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  



export const getDeleteMuscleGroupMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMuscleGroup>>, TError,{muscleGroupId: number}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteMuscleGroup>>, TError,{muscleGroupId: number}, TContext> => {

const mutationKey = ['deleteMuscleGroup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMuscleGroup>>, {muscleGroupId: number}> = (props) => {
          const {muscleGroupId} = props ?? {};

          return  deleteMuscleGroup(muscleGroupId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteMuscleGroupMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMuscleGroup>>>
    
    export type DeleteMuscleGroupMutationError = HTTPValidationError

    /**
 * @summary Delete Muscle Group
 */
export const useDeleteMuscleGroup = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMuscleGroup>>, TError,{muscleGroupId: number}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteMuscleGroup>>,
        TError,
        {muscleGroupId: number},
        TContext
      > => {
      return useMutation(getDeleteMuscleGroupMutationOptions(options), queryClient);
    }
    