/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 0.1.0
 */
import type { ExerciseType } from './exerciseType';

export interface ExerciseCreate {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  type: ExerciseType;
  muscle_group_id: number;
}
