/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 0.1.0
 */
import type { ExerciseType } from './exerciseType';

export interface ExerciseUpdate {
  name?: string | null;
  type?: ExerciseType | null;
  muscle_group_id?: number | null;
}
