/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 0.1.0
 */

export type ExerciseType = typeof ExerciseType[keyof typeof ExerciseType];


export const ExerciseType = {
  weight: 'weight',
  bodyweight: 'bodyweight',
  duration: 'duration',
} as const;
