/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 0.1.0
 */

export interface MuscleGroupRead {
  id: number;
  name: string;
  color: string;
  is_active: boolean;
  created_at: string;
}
