/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 0.1.0
 */

export interface PlanExerciseCreate {
  exercise_id: number;
  sort_order: number;
}
