/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 0.1.0
 */

export interface PlanExerciseRead {
  id: number;
  exercise_id: number;
  sort_order: number;
  exercise_name: string;
  muscle_group_name: string;
}
