/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 0.1.0
 */

export interface UserUpdate {
  username?: string | null;
  email?: string | null;
  password?: string | null;
}
