/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 0.1.0
 */

export interface UserRead {
  id: number;
  username: string;
  email: string;
  is_admin: boolean;
  created_at: string;
}
