/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  MessageResponse,
  MuscleGroupCreate,
  MuscleGroupRead,
  MuscleGroupUpdate
} from '../model';

import { api } from '../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Admin List Muscle Groups
 */
export type adminListMuscleGroupsResponse200 = {
  data: MuscleGroupRead[]
  status: 200
}

export type adminListMuscleGroupsResponseSuccess = (adminListMuscleGroupsResponse200) & {
  headers: Headers;
};
;

export type adminListMuscleGroupsResponse = (adminListMuscleGroupsResponseSuccess)

export const getAdminListMuscleGroupsUrl = () => {


  

  return `/api/v1/admin/muscle-groups`
}

export const adminListMuscleGroups = async ( options?: RequestInit): Promise<adminListMuscleGroupsResponse> => {
  
  return api<adminListMuscleGroupsResponse>(getAdminListMuscleGroupsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getAdminListMuscleGroupsQueryKey = () => {
    return [
    `/api/v1/admin/muscle-groups`
    ] as const;
    }

    
export const getAdminListMuscleGroupsQueryOptions = <TData = Awaited<ReturnType<typeof adminListMuscleGroups>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListMuscleGroups>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListMuscleGroupsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListMuscleGroups>>> = ({ signal }) => adminListMuscleGroups({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListMuscleGroups>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListMuscleGroupsQueryResult = NonNullable<Awaited<ReturnType<typeof adminListMuscleGroups>>>
export type AdminListMuscleGroupsQueryError = unknown


export function useAdminListMuscleGroups<TData = Awaited<ReturnType<typeof adminListMuscleGroups>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListMuscleGroups>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListMuscleGroups>>,
          TError,
          Awaited<ReturnType<typeof adminListMuscleGroups>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListMuscleGroups<TData = Awaited<ReturnType<typeof adminListMuscleGroups>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListMuscleGroups>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListMuscleGroups>>,
          TError,
          Awaited<ReturnType<typeof adminListMuscleGroups>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListMuscleGroups<TData = Awaited<ReturnType<typeof adminListMuscleGroups>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListMuscleGroups>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Admin List Muscle Groups
 */

export function useAdminListMuscleGroups<TData = Awaited<ReturnType<typeof adminListMuscleGroups>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListMuscleGroups>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListMuscleGroupsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Admin Create Muscle Group
 */
export type adminCreateMuscleGroupResponse201 = {
  data: MuscleGroupRead
  status: 201
}

export type adminCreateMuscleGroupResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCreateMuscleGroupResponseSuccess = (adminCreateMuscleGroupResponse201) & {
  headers: Headers;
};
export type adminCreateMuscleGroupResponseError = (adminCreateMuscleGroupResponse422) & {
  headers: Headers;
};

export type adminCreateMuscleGroupResponse = (adminCreateMuscleGroupResponseSuccess | adminCreateMuscleGroupResponseError)

export const getAdminCreateMuscleGroupUrl = () => {


  

  return `/api/v1/admin/muscle-groups`
}

export const adminCreateMuscleGroup = async (muscleGroupCreate: MuscleGroupCreate, options?: RequestInit): Promise<adminCreateMuscleGroupResponse> => {
  
  return api<adminCreateMuscleGroupResponse>(getAdminCreateMuscleGroupUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      muscleGroupCreate,)
  }
);}
  



export const getAdminCreateMuscleGroupMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateMuscleGroup>>, TError,{data: MuscleGroupCreate}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof adminCreateMuscleGroup>>, TError,{data: MuscleGroupCreate}, TContext> => {

const mutationKey = ['adminCreateMuscleGroup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateMuscleGroup>>, {data: MuscleGroupCreate}> = (props) => {
          const {data} = props ?? {};

          return  adminCreateMuscleGroup(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AdminCreateMuscleGroupMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateMuscleGroup>>>
    export type AdminCreateMuscleGroupMutationBody = MuscleGroupCreate
    export type AdminCreateMuscleGroupMutationError = HTTPValidationError

    /**
 * @summary Admin Create Muscle Group
 */
export const useAdminCreateMuscleGroup = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateMuscleGroup>>, TError,{data: MuscleGroupCreate}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCreateMuscleGroup>>,
        TError,
        {data: MuscleGroupCreate},
        TContext
      > => {
      return useMutation(getAdminCreateMuscleGroupMutationOptions(options), queryClient);
    }
    /**
 * @summary Admin Get Muscle Group
 */
export type adminGetMuscleGroupResponse200 = {
  data: MuscleGroupRead
  status: 200
}

export type adminGetMuscleGroupResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminGetMuscleGroupResponseSuccess = (adminGetMuscleGroupResponse200) & {
  headers: Headers;
};
export type adminGetMuscleGroupResponseError = (adminGetMuscleGroupResponse422) & {
  headers: Headers;
};

export type adminGetMuscleGroupResponse = (adminGetMuscleGroupResponseSuccess | adminGetMuscleGroupResponseError)

export const getAdminGetMuscleGroupUrl = (muscleGroupId: number,) => {


  

  return `/api/v1/admin/muscle-groups/${muscleGroupId}`
}

export const adminGetMuscleGroup = async (muscleGroupId: number, options?: RequestInit): Promise<adminGetMuscleGroupResponse> => {
  
  return api<adminGetMuscleGroupResponse>(getAdminGetMuscleGroupUrl(muscleGroupId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getAdminGetMuscleGroupQueryKey = (muscleGroupId: number,) => {
    return [
    `/api/v1/admin/muscle-groups/${muscleGroupId}`
    ] as const;
    }

    
export const getAdminGetMuscleGroupQueryOptions = <TData = Awaited<ReturnType<typeof adminGetMuscleGroup>>, TError = HTTPValidationError>(muscleGroupId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetMuscleGroup>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminGetMuscleGroupQueryKey(muscleGroupId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetMuscleGroup>>> = ({ signal }) => adminGetMuscleGroup(muscleGroupId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(muscleGroupId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminGetMuscleGroup>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminGetMuscleGroupQueryResult = NonNullable<Awaited<ReturnType<typeof adminGetMuscleGroup>>>
export type AdminGetMuscleGroupQueryError = HTTPValidationError


export function useAdminGetMuscleGroup<TData = Awaited<ReturnType<typeof adminGetMuscleGroup>>, TError = HTTPValidationError>(
 muscleGroupId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetMuscleGroup>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetMuscleGroup>>,
          TError,
          Awaited<ReturnType<typeof adminGetMuscleGroup>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetMuscleGroup<TData = Awaited<ReturnType<typeof adminGetMuscleGroup>>, TError = HTTPValidationError>(
 muscleGroupId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetMuscleGroup>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetMuscleGroup>>,
          TError,
          Awaited<ReturnType<typeof adminGetMuscleGroup>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetMuscleGroup<TData = Awaited<ReturnType<typeof adminGetMuscleGroup>>, TError = HTTPValidationError>(
 muscleGroupId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetMuscleGroup>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Admin Get Muscle Group
 */

export function useAdminGetMuscleGroup<TData = Awaited<ReturnType<typeof adminGetMuscleGroup>>, TError = HTTPValidationError>(
 muscleGroupId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetMuscleGroup>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminGetMuscleGroupQueryOptions(muscleGroupId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Admin Update Muscle Group
 */
export type adminUpdateMuscleGroupResponse200 = {
  data: MuscleGroupRead
  status: 200
}

export type adminUpdateMuscleGroupResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminUpdateMuscleGroupResponseSuccess = (adminUpdateMuscleGroupResponse200) & {
  headers: Headers;
};
export type adminUpdateMuscleGroupResponseError = (adminUpdateMuscleGroupResponse422) & {
  headers: Headers;
};

export type adminUpdateMuscleGroupResponse = (adminUpdateMuscleGroupResponseSuccess | adminUpdateMuscleGroupResponseError)

export const getAdminUpdateMuscleGroupUrl = (muscleGroupId: number,) => {


  

  return `/api/v1/admin/muscle-groups/${muscleGroupId}`
}

export const adminUpdateMuscleGroup = async (muscleGroupId: number,
    muscleGroupUpdate: MuscleGroupUpdate, options?: RequestInit): Promise<adminUpdateMuscleGroupResponse> => {
  
  return api<adminUpdateMuscleGroupResponse>(getAdminUpdateMuscleGroupUrl(muscleGroupId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      muscleGroupUpdate,)
  }
);}
  



export const getAdminUpdateMuscleGroupMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateMuscleGroup>>, TError,{muscleGroupId: number;data: MuscleGroupUpdate}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateMuscleGroup>>, TError,{muscleGroupId: number;data: MuscleGroupUpdate}, TContext> => {

const mutationKey = ['adminUpdateMuscleGroup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateMuscleGroup>>, {muscleGroupId: number;data: MuscleGroupUpdate}> = (props) => {
          const {muscleGroupId,data} = props ?? {};

          return  adminUpdateMuscleGroup(muscleGroupId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdateMuscleGroupMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateMuscleGroup>>>
    export type AdminUpdateMuscleGroupMutationBody = MuscleGroupUpdate
    export type AdminUpdateMuscleGroupMutationError = HTTPValidationError

    /**
 * @summary Admin Update Muscle Group
 */
export const useAdminUpdateMuscleGroup = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateMuscleGroup>>, TError,{muscleGroupId: number;data: MuscleGroupUpdate}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdateMuscleGroup>>,
        TError,
        {muscleGroupId: number;data: MuscleGroupUpdate},
        TContext
      > => {
      return useMutation(getAdminUpdateMuscleGroupMutationOptions(options), queryClient);
    }
    /**
 * @summary Admin Delete Muscle Group
 */
export type adminDeleteMuscleGroupResponse200 = {
  data: MessageResponse
  status: 200
}

export type adminDeleteMuscleGroupResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminDeleteMuscleGroupResponseSuccess = (adminDeleteMuscleGroupResponse200) & {
  headers: Headers;
};
export type adminDeleteMuscleGroupResponseError = (adminDeleteMuscleGroupResponse422) & {
  headers: Headers;
};

export type adminDeleteMuscleGroupResponse = (adminDeleteMuscleGroupResponseSuccess | adminDeleteMuscleGroupResponseError)

export const getAdminDeleteMuscleGroupUrl = (muscleGroupId: number,) => {


  

  return `/api/v1/admin/muscle-groups/${muscleGroupId}`
}

export const adminDeleteMuscleGroup = async (muscleGroupId: number, options?: RequestInit): Promise<adminDeleteMuscleGroupResponse> => {
  
  return api<adminDeleteMuscleGroupResponse>(getAdminDeleteMuscleGroupUrl(muscleGroupId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  



export const getAdminDeleteMuscleGroupMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDeleteMuscleGroup>>, TError,{muscleGroupId: number}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof adminDeleteMuscleGroup>>, TError,{muscleGroupId: number}, TContext> => {

const mutationKey = ['adminDeleteMuscleGroup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminDeleteMuscleGroup>>, {muscleGroupId: number}> = (props) => {
          const {muscleGroupId} = props ?? {};

          return  adminDeleteMuscleGroup(muscleGroupId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AdminDeleteMuscleGroupMutationResult = NonNullable<Awaited<ReturnType<typeof adminDeleteMuscleGroup>>>
    
    export type AdminDeleteMuscleGroupMutationError = HTTPValidationError

    /**
 * @summary Admin Delete Muscle Group
 */
export const useAdminDeleteMuscleGroup = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDeleteMuscleGroup>>, TError,{muscleGroupId: number}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminDeleteMuscleGroup>>,
        TError,
        {muscleGroupId: number},
        TContext
      > => {
      return useMutation(getAdminDeleteMuscleGroupMutationOptions(options), queryClient);
    }
    