/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { api } from '../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Health
 */
export type healthApiV1HealthGetResponse200 = {
  data: unknown
  status: 200
}

export type healthApiV1HealthGetResponseSuccess = (healthApiV1HealthGetResponse200) & {
  headers: Headers;
};
;

export type healthApiV1HealthGetResponse = (healthApiV1HealthGetResponseSuccess)

export const getHealthApiV1HealthGetUrl = () => {


  

  return `/api/v1/health`
}

export const healthApiV1HealthGet = async ( options?: RequestInit): Promise<healthApiV1HealthGetResponse> => {
  
  return api<healthApiV1HealthGetResponse>(getHealthApiV1HealthGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getHealthApiV1HealthGetQueryKey = () => {
    return [
    `/api/v1/health`
    ] as const;
    }

    
export const getHealthApiV1HealthGetQueryOptions = <TData = Awaited<ReturnType<typeof healthApiV1HealthGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiV1HealthGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthApiV1HealthGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthApiV1HealthGet>>> = ({ signal }) => healthApiV1HealthGet({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthApiV1HealthGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthApiV1HealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthApiV1HealthGet>>>
export type HealthApiV1HealthGetQueryError = unknown


export function useHealthApiV1HealthGet<TData = Awaited<ReturnType<typeof healthApiV1HealthGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiV1HealthGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthApiV1HealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthApiV1HealthGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthApiV1HealthGet<TData = Awaited<ReturnType<typeof healthApiV1HealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiV1HealthGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthApiV1HealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthApiV1HealthGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthApiV1HealthGet<TData = Awaited<ReturnType<typeof healthApiV1HealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiV1HealthGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health
 */

export function useHealthApiV1HealthGet<TData = Awaited<ReturnType<typeof healthApiV1HealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiV1HealthGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthApiV1HealthGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




